name: website

on:
  push:
    branches: 
      - master


jobs:
  publish:
    steps:
      - name: Check out
        uses: actions/checkout@v1
      
      - name: Build
        run: ./gradlew assemble
      
      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_dir: gogogo-frontend/build/distributions  
    
     
